  CREATE TABLE PHONE_1 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);

  CREATE  TABLE PHONE_2 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);

  CREATE  TABLE PHONE_3 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);

  CREATE  TABLE PHONE_4 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
    CREATE  TABLE PHONE_5 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
    CREATE  TABLE PHONE_6 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
    CREATE  TABLE PHONE_7 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
    CREATE  TABLE PHONE_8 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
    CREATE  TABLE PHONE_9 (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
  CREATE  TABLE AddressBook (
  contactsId  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  poBox TEXT NULL ,
  addType TEXT NULL ,
  country TEXT NULL ,
  postalcode TEXT NULL ,
  street TEXT NULL ,
  location TEXT NULL ,
  region TEXT NULL ,
  lan TEXT NULL ,
  lon TEXT NULL ,
  label TEXT NULL ,
  email TEXT NULL ,
  url TEXT NULL ,
  telephone TEXT NULL ,
  homeNumber TEXT NULL ,
  mobileNumber TEXT NULL ,
  workNumber TEXT NULL ,
  otherNumber TEXT NULL);
  
  CREATE TABLE BT_DEVICE (
  bdDeviceId INT NOT NULL,
  bdAddr TEXT NOT NULL ,
  tableName NAME TEXT NOT NULL,
  syncComplete  INTEGER,
  PRIMARY KEY (bdDeviceId) );

  CREATE  TABLE SpeedDial (
  speedDialNumber  INTEGER PRIMARY KEY,
  familyName TEXT NULL ,
  givenName TEXT NULL ,
  formattedName TEXT NULL ,
  phoneNumber TEXT NULL
  );
